kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kaniko-cache-claim
spec:
  storageClassName: kaniko-cache-volume
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 8Gi