apiVersion: v1
kind: Pod
metadata:
  name: kaniko-warmer
  namespace: jenkins
spec:
  containers:
  - name: kaniko-warmer
    image: gcr.io/kaniko-project/warmer:latest
    imagePullPolicy: IfNotPresent
    args: ["--cache-dir=/cache",
           "--image=alpine:3.14"]
    volumeMounts:
      - name: jenkins-docker-cfg
        mountPath: /kaniko/.docker
      - name: kaniko-cache
        mountPath: /cache
  restartPolicy: Never
  volumes:
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: container-registry-credentials
          items:
            - key: .dockerconfigjson
              path: config.json
  - name: kaniko-cache
    persistentVolumeClaim:
      claimName: kaniko-cache-claim