apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  labels:
    jenkins-build: app-build
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor@sha256:0d8408715c7bcc2dc747405936c0e72665cafb2357fb78e23eb71f90bc39624f
    imagePullPolicy: Always
    command:
    - sleep
    args:
    - 99d
    tty: true
    volumeMounts:
      - name: jenkins-docker-cfg
        mountPath: /kaniko/.docker
      - name: kaniko-cache
        mountPath: /cache
  volumes:
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: container-registry-credentials
          items:
            - key: .dockerconfigjson
              path: config.json
  - name: kaniko-cache
    persistentVolumeClaim:
      claimName: kaniko-cache-claim