apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-controller-volume
  namespace: jenkins
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/jenkins-volume/
