apiVersion: v1
kind: PersistentVolume
metadata:
  name: container-registry-volume
  namespace: jenkins
spec:
  storageClassName: container-registry-volume
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/container-registry-volume/
